version: '3'

services:

  # kafka_app:
  #   container_name: kafka_app
  #   build: ./app
  #   ports:
  #     - 1337:1337
  #   volumes:
  #     - ./app/:/usr/src/app
  #   networks:
  #     - kafka-net

  kafka_mysql:
    hostname: kafka_mysql
    container_name: kafka_mysql
    image: mysql:8.1
    restart: always
    expose:
      - 3306
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=kafka_db_example
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - kafka-net

  kafka_elasticsearch:
    image: elasticsearch:8.12.2
    container_name: kafka_elasticsearch
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - kafka-net

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka-net:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "commerce_module:1:1"
    networks:
      - kafka-net

  kafka_connect:
    build: ./kafka_connect
    container_name: kafka_connect
    depends_on:
      - zookeeper
      - kafka
      - kafka_mysql
      - kafka_elasticsearch
    networks:
      - kafka-net

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - zookeeper
      - kafka
      - kafka_connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka_connect:8083
      PORT: 9021
    networks:
      - kafka-net

  kafka_kibana:
    image: kibana:8.12.2
    container_name: kafka_kibana
    ports:
      - 5601:5601
    depends_on:
      - kafka_elasticsearch
    environment:
      ELASTICSEARCH_URL: http://kafka_elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://kafka_elasticsearch:9200"]'
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge